version: '3.8'

services:
  letta_db:
    image: ankane/pgvector:v0.5.1
    networks:
      - default
    environment:
      - POSTGRES_USER=${LETTA_PG_USER:-letta}
      - POSTGRES_PASSWORD=${LETTA_PG_PASSWORD:-letta}
      - POSTGRES_DB=${LETTA_PG_DB:-letta}
    ports:
      - "5432:5432"

  letta_server:
    image: lettaai/letta:latest
    hostname: mythos-letta_server-1
    networks:
      - default
    depends_on:
      - letta_db
    ports:
      - "8083:8083"
      - "8283:8283"
    env_file:
      - .env
    environment:
      - LETTA_PG_DB=${LETTA_PG_DB:-letta}
      - LETTA_PG_USER=${LETTA_PG_USER:-letta}
      - LETTA_PG_PASSWORD=${LETTA_PG_PASSWORD:-letta}
      - LETTA_PG_HOST=pgvector_db
      - LETTA_PG_PORT=5432

  letta_nginx:
    hostname: mythos-letta_nginx-1
    image: nginx:stable-alpine3.17-slim
    networks:
      - default
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/mythos.fabryx.org:/etc/nginx/ssl/live:ro
      - /etc/letsencrypt/archive/mythos.fabryx.org:/etc/nginx/ssl/archive:ro
    ports:
      - "8082:8082"
      - "443:443"

networks:
  default:
    name: mythos_network
